version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: area
    ports:
      - "5432:5432"
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: always

  server:
    container_name: server
    build: './server'
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: ${API_PORT}
      NGROK_SUBOMAIN: ${NGROK_SUBOMAIN}
      RIOT_API_KEY: ${RIOT_API_KEY}
      OUTLOOK_CLIENT_ID: ${OUTLOOK_CLIENT_ID}
      OUTLOOK_CLIENT_SECRET: ${OUTLOOK_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      DROPBOX_CLIENT_SECRET: ${DROPBOX_CLIENT_SECRET}
      DISCOGS_CLIENT_ID: ${DISCOGS_CLIENT_ID}
      DISCOGS_CLIENT_SECRET: ${DISCOGS_CLIENT_SECRET}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      NGROK_AUTH_TOKEN: 1XQZRanioiWKnYtTOKXepFnwBFc_738EwK8Eec39Qa64QhXhD
    networks:
      - server-network
      - db-network
    volumes:
      - ./server:/server
      - /server/node_modules

  client_mobile:
    container_name: client_mobile
    build: './mobile_client'
    restart: 'no'
    volumes:
      - ./apk_file:/shared

  client_web:
    container_name: client_web
    build: './web_client'
    restart: always
    ports:
        - "8081:3000"
    networks:
        - server-network
    depends_on:
      - server
      - client_mobile
    volumes:
      - ./apk_file:/usr/app/public/apk
      - ./web_client/src:/usr/app/src

networks:
  server-network:
  db-network:

volumes:
  db-data:
